LLVM_ROOT=/root/llvm-16.0.0
export PATH=$LLVM_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$LLVM_ROOT/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LLVM_ROOT/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$LLVM_ROOT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$LLVM_ROOT/include:$CPLUS_INCLUDE_PATH

