PAPI_ROOT=`pwd`/papi-6.0.0/install
export PATH=$PAPI_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$PAPI_ROOT/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$PAPI_ROOT/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$PAPI_ROOT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$PAPI_ROOT/include:$CPLUS_INCLUDE_PATH

LLVM_ROOT=`pwd`/llvm-8.0.0/install
export PATH=$LLVM_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$LLVM_ROOT/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LLVM_ROOT/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$LLVM_ROOT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$LLVM_ROOT/include:$CPLUS_INCLUDE_PATH

